analytics:
  provider:
    "google-gtag"
    # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-KWF4L4J755"
    anonymize_ip: # true, false (default)
